# Yarn Configuration
nodeLinker: node-modules
enableGlobalCache: false
compressionLevel: mixed

# Workspace configuration
enableWorkspaces: true

# Network configuration
networkTimeout: 300000
httpTimeout: 300000
